# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0928b1cf2e541377ecd7d1935d345bbb0e347d9d14a4e1fa54e608fe6bfadf3aed8df72e432ed6079b6192d748b6affa0f8d31336aedbd172a6435ea03c243ba

test:
  secret_key_base: b54402a01f7e6a273236624ada5892ce0f45301310d06156f017b994df3f33f67ab67d8ddbd605af86b5bba945686b11a79f39da5fe0ded2aa4cc39d58a62ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
